buildscript {
    repositories {
        mavenCentral()
    }
    dependencies {
        classpath "org.flywaydb:flyway-database-postgresql:12.4.0"
    }
}

plugins {
    id 'java'
    id 'application'
    id 'org.jetbrains.kotlin.jvm' version '2.3.21'
    id 'org.jetbrains.kotlin.plugin.spring' version '2.3.21'
    id 'org.springframework.boot' version '4.1.0'
    id 'io.spring.dependency-management' version '1.1.7'
    id 'org.flywaydb.flyway' version '12.4.0'
}

application {
    mainClass = 'org.mikita.bankingsystemslab.user.MainKt'
}

group = 'org.mikita.bankingsystemslab'
version = '0.0.1-SNAPSHOT'

repositories {
    mavenCentral()
}

dependencies {
    implementation 'org.springframework.boot:spring-boot-starter'
    implementation 'org.springframework.boot:spring-boot-starter-jdbc'
    implementation 'org.springframework.boot:spring-boot-starter-web'
    implementation 'org.springframework.boot:spring-boot-starter-flyway'

    implementation 'org.jetbrains.kotlin:kotlin-reflect'

    implementation "org.flywaydb:flyway-core"
    implementation "org.flywaydb:flyway-database-postgresql"

    runtimeOnly 'org.postgresql:postgresql'

    testImplementation 'org.jetbrains.kotlin:kotlin-test-junit5'
    testImplementation 'org.springframework.boot:spring-boot-starter-test'
    testImplementation 'org.junit.jupiter:junit-jupiter'
    testImplementation "io.mockk:mockk-jvm:1.14.11"
    testImplementation 'org.testcontainers:testcontainers:2.0.5'
    testImplementation 'org.testcontainers:testcontainers-postgresql:2.0.5'
    testImplementation 'org.testcontainers:testcontainers-junit-jupiter:2.0.5'

    testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
}

flyway {
    url = "jdbc:postgresql://localhost:5432/account-service-db"
    user = System.getenv("DB_USERNAME")
    password = System.getenv("DB_PASSWORD")
    schemas = ["public"]
    locations = ["classpath:db/migration"]
    cleanDisabled = false
}

test {
    useJUnitPlatform()
}

kotlin {
    jvmToolchain(25)
}

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(25)
    }
}

tasks.register('integrationTest', Test) {

    testClassesDirs = tasks.named('test').get().testClassesDirs
    classpath = tasks.named('test').get().classpath

    useJUnitPlatform()

    filter {
        includeTestsMatching "org.mikita.bankingsystemslab.transaction.api.*"
    }
}

tasks.register("initDb") {
    dependsOn("clean", "build", "flywayClean", "flywayMigrate")
}

tasks.named("build") {
    mustRunAfter("clean")
}

tasks.named("flywayClean") {
    mustRunAfter("build")
}

tasks.named("flywayMigrate") {
    mustRunAfter("flywayClean")
}
